name: Secrets guard

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.gif"
      - "**/*.svg"

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run pre-commit (detect-secrets)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - name: Ensure baseline exists
        run: |
          test -f .secrets.baseline || (echo "::error ::.secrets.baseline missing"; exit 1)
